export const navbar = [
  { Name: "Home", path: "/" },
  { Name: "About", path: "/About" },
  { Name: "Blogs", path: "/Blogs" },
  { Name: "Categories", path: "/Categories" },
  { Name: "Write a Blog", path: "/Write-Blog" },
  { Name: "Authors", path: "/Authors" },
];

const professions = [
  "software-developer",
  "data-scientist",
  "graphic-designer",
  "product-manager",
  "digital-marketer",
  "content-writer",
  "civil-engineer",
  "mechanical-engineer",
  "electrical-engineer",
  "biomedical-engineer",
  "game-developer",
  "ai-researcher",
  "cybersecurity-analyst",
  "blockchain-developer",
  "business-analyst",
  "financial-analyst",
  "ui-ux-designer",
  "web-developer",
  "cloud-engineer",
  "network-engineer",
  "machine-learning-engineer",
  "project-manager",
  "photographer",
  "video-editor",
  "architect",
  "teacher",
  "journalist",
  "lawyer",
  "doctor",
  "nurse",
  "chef",
  "artist",
  "entrepreneur",
  "economist",
  "environmental-scientist",
  "researcher",
  "social-media-manager",
  "sales-executive",
  "human-resource-manager",
  "operations-manager",
  "other"
];

const blogCategories = [
  "technology",
  "science",
  "education",
  "health-wellness",
  "fitness",
  "travel",
  "food-recipes",
  "lifestyle",
  "personal-finance",
  "investments",
  "business",
  "entrepreneurship",
  "marketing",
  "social-media",
  "parenting",
  "relationships",
  "self-improvement",
  "productivity",
  "mental-health",
  "environment",
  "sustainability",
  "entertainment",
  "movies",
  "books",
  "gaming",
  "fashion",
  "beauty",
  "photography",
  "art-culture",
  "history",
  "politics",
  "sports",
  "automotive",
  "diy-crafts",
  "pets",
  "coding-programming",
  "artificial-intelligence",
  "web-development",
  "mobile-development",
  "data-science",
  "cloud-computing",
  "machine-learning",
  "blockchain",
  "cryptocurrency",
  "augmented-reality",
  "virtual-reality",
  "career-development",
  "interviews",
  "college-life",
  "study-abroad",
  "exams-preparation",
  "spirituality",
  "mindfulness",
  "hobbies",
  "home-garden",
  "other"
];

export { professions, blogCategories };
