export const navbar = [
  { Name: "Home", path: "/" },
  { Name: "About", path: "/About" },
  { Name: "Blogs", path: "/Blogs" },
  { Name: "Categories", path: "/Categories" },
  { Name: "Write a Blog", path: "/Write-Blog" },
  { Name: "Authors", path: "/Authors" },
];

const professions = [
  "software-developer",
  "data-scientist",
  "graphic-designer",
  "product-manager",
  "digital-marketer",
  "content-writer",
  "civil-engineer",
  "mechanical-engineer",
  "electrical-engineer",
  "biomedical-engineer",
  "game-developer",
  "ai-researcher",
  "cybersecurity-analyst",
  "blockchain-developer",
  "business-analyst",
  "financial-analyst",
  "ui-ux-designer",
  "web-developer",
  "cloud-engineer",
  "network-engineer",
  "machine-learning-engineer",
  "project-manager",
  "photographer",
  "video-editor",
  "architect",
  "teacher",
  "journalist",
  "lawyer",
  "doctor",
  "nurse",
  "chef",
  "artist",
  "entrepreneur",
  "economist",
  "environmental-scientist",
  "researcher",
  "social-media-manager",
  "sales-executive",
  "human-resource-manager",
  "operations-manager",
  "other"
];


export { professions };
